name: Build DEV

on:
  push:
    branches: [ main ]

jobs:
  build-docker:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    needs: quality-gate

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: cloverink
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/cloverink/docker-django:latest
            ghcr.io/cloverink/docker-django:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
